Global:
  use_gpu: True
  use_amp: True
  epoch_num: 150
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/rec_svtr_small_en/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 10]
  cal_metric_during_train: True
  pretrained_model: /home/huan/Downloads/rec_svtr_small_none_ctc_en_train/best_accuracy.pdparams
  # pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: 
  # for data or label process
  character_dict_path: /home/huan/prjdir/PaddleOCR/dicts/num_dict.txt
  character_type: en
  max_text_length: 8
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_svtr_tiny.txt


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 0.00000008
  weight_decay: 0.045
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.0003
    warmup_epoch: 2

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    # name: STN_ON
    # tps_inputsize: [32, 64]
    # tps_outputsize: [48, 96]
    # num_control_points: 20
    # tps_margins: [0.05,0.05]
    # stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [48, 96]
    out_char_num: 8
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [96, 192, 256]
    depth: [3, 6, 6]
    num_heads: [3, 6, 8]
    mixer: ['Local','Local','Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /mnt/sdb/vollmont_data/NPR_OCR/dataset/train/
    label_file_list: /mnt/sdb/vollmont_data/NPR_OCR/dataset/train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          image_shape: [3, 48, 96]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /mnt/sdb/vollmont_data/NPR_OCR/dataset/eval/
    label_file_list: /mnt/sdb/vollmont_data/NPR_OCR/dataset/eval.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - SVTRRecResizeImg:
          image_shape: [3, 48, 96]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 4